"""Inicijalna tablica najmovi

Revision ID: 4cd6c27f7cd0
Revises: 
Create Date: 2026-05-22 19:29:13.514142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd6c27f7cd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('najmovi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_preuzimanja', sa.Date(), nullable=False),
    sa.Column('datum_povrata', sa.Date(), nullable=False),
    sa.Column('ukupna_cijena', sa.Float(), nullable=False),
    sa.Column('korisnik_id', sa.Integer(), nullable=True),
    sa.Column('vozilo_id', sa.Integer(), nullable=True),
    sa.Column('lokacija_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnici.id'], ),
    sa.ForeignKeyConstraint(['lokacija_id'], ['lokacije.id'], ),
    sa.ForeignKeyConstraint(['vozilo_id'], ['vozila.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('najmovi')
    # ### end Alembic commands ###
